services:
  drupal:
    image: drupal:10
    container_name: drupal_local
    ports:
      - "8080:80"
    volumes:
      - ./drupal-docker:/var/www/html
    restart: always
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: drupal_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal-docker
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    restart: always

volumes:
  db_data:
